### ISSUE TITLE
No Qt Creator project file.

### ISSUE THREAD

**Issue by shujaatak** [picolloo/QT-Cad#1]
This project seems good but as the project is not well organized so it is hard to compile. You should create a Qt Creator project .pro and keep everything within the working directory so that anyone can easily compile your project for testing. 
Furthermore, boost is an awesome library but for the project like this one should try to not use external libraries.
As it's your project so it's up to you what you do but the people like me who are interested in your project may not be ever able to compile it as easily as it should be.

**Comment by pikonha** [comment]
Oh sorry, I didn't notice your issues. I'll try to fix it up as soon as possible. Thanks for the contribuition;
