### ISSUE TITLE
Re-structured version of your QT-Cad 

### ISSUE THREAD

**Issue by shujaatak** [picolloo/QT-Cad#4]
I have created a re-structured version of your QT-Cad. It is same as your's but I have removed the CMake and Boost dependency. I have made this project with QtCreator. It can be compiled with both MinGW and MSVC compilers. **You can copy all the code to your repository as it is YOUR CODE!** Here is the link to my version: https://github.com/shujaatak/QtCAD

**Comment by pikonha** [comment]
That's awesome!

**Comment by pikonha** [comment]
I've to use cmake to pratice for my job so I'll still using it.
